version: 2

jobs:
  docs-build:
    docker:
      - image: ruby:2.6
    steps:
      - checkout
      - run:
          name: Install AsciiDoctor & Rouge
          command: |
            gem install asciidoctor
            gem install rouge -v 3.3.0
      - run:
          name: Build Site
          command: asciidoctor -a toc="left" -a toclevels=2 README.adoc -o _build/html/index.html
      - persist_to_workspace:
          root: _build
          paths: html
  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: _build
      - run:
          name: Disable jekyll builds
          command: touch _build/html/.nojekyll
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "roimisia@gmail.com"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "cf:04:50:6a:b9:76:da:78:66:57:31:74:e8:35:89:6f"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages -add --dotfiles --message "[skip ci] Update site" --dist _build/html

workflows:
  version: 2
  build:
    jobs:
      - docs-build
      - docs-deploy:
          requires:
            - docs-build
          filters:
            branches:
              only: ja
